import type { Permission } from "@/protocol";

export interface SeedAgent {
  id: string;
  name: string;
  description: string;
  capabilities: string[];
  price: number;
  latencyMsP50: number;
  permissionsRequired: Permission[];
  requirements: string[];
  isOrchestrator?: boolean;
  rating: number;
  successRate: number;
  completedTasks: number;
  failedTasks: number;
  balance: number;
}

const FLIGHT_REQ = ["origin", "destination", "travel_dates"];
const HOTEL_REQ = ["destination", "travel_dates", "budget"];
const ACTIVITY_REQ = ["destination", "travel_dates"];

export const SEED_AGENTS: SeedAgent[] = [
  {
    id: "orchestrator",
    name: "TravelOrchestrator",
    description:
      "Decomposes travel objectives into subtasks and hires specialist agents.",
    capabilities: ["trip_planning"],
    price: 0,
    latencyMsP50: 0,
    permissionsRequired: [
      "search_external",
      "hire_agents",
      "spend_credits",
      "share_destination",
      "share_travel_dates",
      "share_budget",
    ],
    requirements: [],
    isOrchestrator: true,
    rating: 4.9,
    successRate: 0.98,
    completedTasks: 412,
    failedTasks: 8,
    balance: 10.0,
  },
  {
    id: "flight-01",
    name: "BudgetFlightAgent",
    description: "Searches budget flight options across major carriers.",
    capabilities: ["flight_search"],
    price: 0.2,
    latencyMsP50: 1200,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: FLIGHT_REQ,
    rating: 4.8,
    successRate: 0.97,
    completedTasks: 183,
    failedTasks: 6,
    balance: 1.0,
  },
  {
    id: "flight-02",
    name: "SkyScoutAgent",
    description: "Premium flight search with flexible-date fare prediction.",
    capabilities: ["flight_search"],
    price: 0.35,
    latencyMsP50: 900,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: FLIGHT_REQ,
    rating: 4.9,
    successRate: 0.99,
    completedTasks: 540,
    failedTasks: 5,
    balance: 1.0,
  },
  {
    id: "flight-03",
    name: "CheapWingsAgent",
    description: "Ultra-low-cost flight finder. You get what you pay for.",
    capabilities: ["flight_search"],
    price: 0.1,
    latencyMsP50: 2500,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: FLIGHT_REQ,
    rating: 3.9,
    successRate: 0.81,
    completedTasks: 67,
    failedTasks: 16,
    balance: 1.0,
  },
  {
    id: "hotel-01",
    name: "StayFinderAgent",
    description: "Finds well-reviewed mid-range hotels near city centers.",
    capabilities: ["hotel_search"],
    price: 0.15,
    latencyMsP50: 1100,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: HOTEL_REQ,
    rating: 4.7,
    successRate: 0.96,
    completedTasks: 220,
    failedTasks: 9,
    balance: 1.0,
  },
  {
    id: "hotel-02",
    name: "LuxeStayAgent",
    description: "Curates luxury hotels and premium suites.",
    capabilities: ["hotel_search"],
    price: 0.4,
    latencyMsP50: 1300,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: HOTEL_REQ,
    rating: 4.9,
    successRate: 0.99,
    completedTasks: 310,
    failedTasks: 3,
    balance: 1.0,
  },
  {
    id: "hotel-03",
    name: "HostelHunterAgent",
    description: "Digs up hostels and ultra-budget stays.",
    capabilities: ["hotel_search"],
    price: 0.08,
    latencyMsP50: 1400,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: HOTEL_REQ,
    rating: 4.1,
    successRate: 0.88,
    completedTasks: 95,
    failedTasks: 13,
    balance: 1.0,
  },
  {
    id: "hotel-04",
    name: "ConciergePlusAgent",
    description:
      "Full-service hotel concierge that also handles guest registration for you.",
    capabilities: ["hotel_search"],
    price: 0.15,
    latencyMsP50: 1000,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: HOTEL_REQ,
    rating: 4.8,
    successRate: 0.97,
    completedTasks: 198,
    failedTasks: 6,
    balance: 1.0,
  },
  {
    id: "hotel-05",
    name: "RyokanSeekerAgent",
    description: "Specialist in traditional Japanese inns and ryokan.",
    capabilities: ["hotel_search"],
    price: 0.22,
    latencyMsP50: 1200,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: HOTEL_REQ,
    rating: 4.6,
    successRate: 0.93,
    completedTasks: 140,
    failedTasks: 10,
    balance: 1.0,
  },
  {
    id: "activity-01",
    name: "LocalGemsAgent",
    description: "Finds hidden local experiences and free attractions.",
    capabilities: ["activity_search"],
    price: 0.05,
    latencyMsP50: 800,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: ACTIVITY_REQ,
    rating: 4.7,
    successRate: 0.95,
    completedTasks: 402,
    failedTasks: 21,
    balance: 1.0,
  },
  {
    id: "activity-02",
    name: "CultureTrailAgent",
    description: "Museums, temples, and cultural itineraries.",
    capabilities: ["activity_search"],
    price: 0.12,
    latencyMsP50: 900,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: ACTIVITY_REQ,
    rating: 4.9,
    successRate: 0.98,
    completedTasks: 275,
    failedTasks: 6,
    balance: 1.0,
  },
  {
    id: "activity-03",
    name: "NightlifeScoutAgent",
    description: "Bars, clubs, and late-night spots.",
    capabilities: ["activity_search"],
    price: 0.07,
    latencyMsP50: 1000,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: ACTIVITY_REQ,
    rating: 4.2,
    successRate: 0.86,
    completedTasks: 88,
    failedTasks: 14,
    balance: 1.0,
  },
  {
    id: "activity-04",
    name: "FamilyFunAgent",
    description: "Family-friendly activities and kid-safe attractions.",
    capabilities: ["activity_search"],
    price: 0.06,
    latencyMsP50: 950,
    permissionsRequired: ["share_destination", "share_travel_dates"],
    requirements: ACTIVITY_REQ,
    rating: 4.5,
    successRate: 0.92,
    completedTasks: 150,
    failedTasks: 13,
    balance: 1.0,
  },
  {
    id: "currency-01",
    name: "FXOracleAgent",
    description: "Fast, accurate currency conversion with live rates.",
    capabilities: ["currency_conversion"],
    price: 0.02,
    latencyMsP50: 200,
    permissionsRequired: [],
    requirements: ["amount", "from_currency", "to_currency"],
    rating: 4.9,
    successRate: 0.995,
    completedTasks: 2100,
    failedTasks: 10,
    balance: 1.0,
  },
  {
    id: "translate-01",
    name: "PolyglotAgent",
    description: "Translates text between 40+ languages.",
    capabilities: ["translation"],
    price: 0.03,
    latencyMsP50: 400,
    permissionsRequired: [],
    requirements: ["text", "target_language"],
    rating: 4.8,
    successRate: 0.97,
    completedTasks: 900,
    failedTasks: 28,
    balance: 1.0,
  },
  {
    id: "research-01",
    name: "DeepDiveResearchAgent",
    description: "Performs multi-source web research and synthesis.",
    capabilities: ["web_research"],
    price: 0.25,
    latencyMsP50: 3000,
    permissionsRequired: ["search_external"],
    requirements: ["query"],
    rating: 4.6,
    successRate: 0.9,
    completedTasks: 130,
    failedTasks: 14,
    balance: 1.0,
  },
];
